name: 'Phpcs and reviewdog runner'
description: 'This action installs reviewdog ðŸ¶, runs phpcs ðŸ˜ and pipes output to reviewdog. It depends '
inputs:
  reviewdog_version:
    description: 'reviewdog version. [latest,nightly,vX.Y.Z]'
    default: 'latest'
  reviewdog_token:
    description: 'The Github API token needed for Reviewdog'
runs:
  using: 'composite'
  steps:
    - name: Install phpcs
      run: $GITHUB_ACTION_PATH/install.sh
      env:
        REVIEWDOG_VERSION: ${{ inputs.reviewdog_version }}
        REVIEWDOG_TEMPDIR: ${{ runner.temp }}
    - name: Run phpcs and report to reviewdog
      run: |
        echo 'NO shell: bash'
        set -x
        set +o
        phpcs --config-set ignore_errors_on_exit 1
        phpcs --config-set ignore_warnings_on_exit 1
        $(composer config bin-dir)/phpcs --report=checkstyle > /tmp/phpcs-report
        cat /tmp/phpcs-report
        cat /tmp/phpcs-report | reviewdog -f=checkstyle -name=phpcs -reporter=github-pr-check
        echo "exit code is $?"
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.reviewdog_token }}

branding:
  icon: 'terminal'
  color: 'gray-dark'