name: 'Phpcs and reviewdog runner'
description: 'This action installs reviewdog ðŸ¶, runs phpcs ðŸ˜ and pipes output to reviewdog. It depends '
inputs:
  reviewdog_version:
    description: 'reviewdog version. [latest,nightly,vX.Y.Z]'
    default: 'latest'
  reviewdog_token:
    description: 'The Github API token needed for Reviewdog'
runs:
  using: 'composite'
  steps:
    - name: Install phpcs
      run: $GITHUB_ACTION_PATH/install.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: ${{ inputs.reviewdog_version }}
        REVIEWDOG_TEMPDIR: ${{ runner.temp }}
    - name: Verify phpcs
      run: |
        echo "::group::ðŸ“– reviewdog -h"
        reviewdog -h 2>&1 || true
        echo "::endgroup::"
      shell: bash
    - name: Run phpcs and report to reviewdog
      run: |
        $(composer config bin-dir)/phpcs --report=checkstyle | reviewdog -f=checkstyle -name=phpcs -reporter=github-pr-check
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.reviewdog_token }}

branding:
  icon: 'terminal'
  color: 'gray-dark'