name: update-reviewdog
on:
  schedule:
    - cron:  '14 14 * * *'
  workflow_dispatch:
  push: # for testing
    branches:
      - '**'

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-depup@master
        id: update-reviewdog
        with:
          file: action.yml
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update ${{ steps.update-reviewdog.outputs.repo }} to ${{ steps.update-reviewdog.outputs.latest }}"
          commit-message: "Update ${{ steps.update-reviewdog.outputs.repo }} to ${{ steps.update-reviewdog.outputs.latest }}"
          body: |
            Update ${{ steps.update-reviewdog.outputs.repo }} to [${{ steps.update-reviewdog.outputs.latest }}](https://github.com/${{ steps.update-reviewdog.outputs.repo }}/releases/tag/v${{ steps.update-reviewdog.outputs.latest }})
            This PR is auto generated by [update-reviewdog workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: update-reviewdog/${{ steps.update-reviewdog.outputs.repo }}
          base: main
